### PR TITLE
@Crosa - Allow users to pass lighthouse flags through the command line

### PR DESCRIPTION
**Pull request by celsosantarosa**
Enable users to call the lighthouse-ci and pass lighthouse flags, for instance:

lighthouse-ci <url> --emulated-form-factor desktop --seo 92

### CODE REVIEW

**Comment by andreasonny83** [comment]
Thanks @celsosantarosa . That looks awesome. However I recently moved the `lib/cli.js` file under the `bin` folder where I also fixed an issue related to the `best-practices` flag #16 . 
Are you able to merge in the latest changes from the `master` branch so I can proceed and accept your PR?

**Comment by celsosantarosa** [comment]
Hi @andreasonny83,

Just implemented the changes we asked. Thank you for calling out the CLI issue.

**Comment by andreasonny83** [comment]
closes #9

**Comment by DavidReinberger** [comment]
Hi! I'm trying to use this feature unfortunately I had no luck with it, I'm running the CI with this command `lighthouse-ci --preset perf -GA ./lighthouseArtifacts http://localhost:5000/community --report .`

**Comment by andreasonny83** [comment]
@DavidReinberger you can pass any native Lighthouse flag to lighthouse-ci. Please have a look at this section of the readme and please, let me know if that solves your problem: https://github.com/andreasonny83/lighthouse-ci#lighthouse-flags

**Comment by celsosantarosa** [comment]
Hi @DavidReinberger,

Are you using the most recent version of lighthouse? I'm using lighthouse 1.3.0 and everything is working as expected. Here is how I am calling lighthouse-ci:

lighthouse-ci $URL --report $REPORT_PATH --performance $PERFORMANCE_THRESHOLD --pwa $PWA_THRESHOLD --accessibility $ACCESSIBILTY_THRESHOLD --best-practices $BEST_PRACTICE_THRESHOLD --seo $SEO_THRESHOLD --emulated-form-factor $EMULATED_FORM_FACTOR

Hope It helps you.

**Comment by andreasonny83** [comment]
I'm going to archive the conversation as it belongs to an already resolved PR. @DavidReinberger, if the explanation from @celsosantarosa doesn't solve your problems, please create a dedicated issue so other people can benefit from that. Thank you

**Pull request merged**
